theme: jekyll-theme-minimal
permalink: /journal/:year/:month/:day/:title/
author: Vinay
url: "https://vinayk94.github.io/"
baseurl: "/dailylog"

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/posts/page:num/"
markdown: GFM
