title: Vinay's Blog
#theme: jekyll-theme-minimal
permalink: /journal/:year/:month/:day/:title/
author: Vinay
url: "https://vinayk94.github.io/"
baseurl: "/dailylog"


markdown: kramdown
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
kramdown:
  parse_block_html: true


include:
  - _includes

#plugins:
#  - jekyll-paginate

paginate: 10
paginate_path: "/posts/page:num/"
#markdown: GFM


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
