title: Vinay's Blog
#theme: jekyll-theme-minimal
permalink: /journal/:year/:month/:day/:title/
author: Vinay
url: "https://vinayk94.github.io/"
baseurl: "/dailylog"


markdown: kramdown
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
kramdown:
  parse_block_html: true


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


include:
  - _includes

#plugins:
#  - jekyll-paginate

paginate: 10
paginate_path: "/posts/page:num/"
#markdown: GFM


# Other settings
show_excerpts: true