name: Deploy Projects Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ruby-build and Dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential libssl-dev libreadline-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git /tmp/ruby-build
          sudo /tmp/ruby-build/install.sh

      - name: Manually Install Ruby in Runner Tool Cache
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Set up Ruby (Should Now Work)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3

      - name: Check Token Access
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN is not set!"
          else
            echo "GH_TOKEN is available."
          fi

      - name: Fetch GitHub Projects
        run: |
          mkdir -p _data  # Ensure the _data directory exists
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/users/vinayk94/repos -o _data/projects.json
          cat _data/projects.json  # Add this line to log the contents of the JSON file
      - name: Build and deploy
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
          echo "Deploying site"
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
          PAGES_REPO_NWO: vinayk94/dailylog
