name: Deploy Projects Page

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system Ruby and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          
          # Set up gems to install in user's home directory
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          
          # Install Jekyll and Bundler
          gem install jekyll bundler
          
          # Install GitHub Pages dependencies
          gem install github-pages

      - name: Build site
        run: |
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site