name: Deploy Projects Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  #  (adjust if needed)
          bundler-cache: true  # Caches 'bundle install' results for faster future builds

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Check Token Access
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN is not set!"
          else
            echo "GH_TOKEN is available."
          fi


      - name: Fetch GitHub Projects
        run: |
          mkdir -p _data  # Ensure the _data directory exists
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/users/vinayk94/repos -o _data/projects.json
          cat _data/projects.json  # Add this line to log the contents of the JSON file
      - name: Build and deploy
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
          echo "Deploying site"
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
          PAGES_REPO_NWO: vinayk94/dailylog
