name: Deploy Projects Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Print Directories
        run: |
          pwd
          ls -la
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"