name: Deploy Projects Page

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 3.1.4

jobs:
  pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Pre-ruby setup
        run: |
          sudo apt-get update
          sudo apt-get install -y git autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo chown -R $USER:$USER /opt/hostedtoolcache/Ruby
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby using setup-ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.1.4'

      - name: Build and deploy
        run: |
          gem install bundler -v 2.4.22
          bundle install
          bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site