name: Deploy Projects Page

on:
  push:
    branches:
      - main

jobs:
  pages:  # Changed from 'build' to 'pages'
    runs-on: ubuntu-24.04
    
    steps:
      - name: Debug Setup
        run: |
          ls -la /
          ls -la $HOME
          ls -la $GITHUB_WORKSPACE || echo "Workspace not setup yet"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true  # Ensure clean checkout
          
      - name: Basic Setup
        run: |
          ls -la
          echo "Current location: $(pwd)"
          echo "Found files:"
          find . -name ".ruby-*"