name: Deploy Projects Page

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10  
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install ruby-build and Dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential libssl-dev libreadline-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git /tmp/ruby-build
          sudo /tmp/ruby-build/install.sh
      
      - name: Manually Install Ruby in Runner Tool Cache
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo chown -R $USER:$USER /opt/hostedtoolcache/Ruby/3.1.4
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
      
      - name: Fetch GitHub Projects
        run: |
          mkdir -p _data
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/users/vinayk94/repos" \
            -o _data/projects.json
      
      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site