name: Deploy Projects Page

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.195.0
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site