name: Deploy Projects Page

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install RVM and Ruby
        run: |
          # Install RVM GPG keys
          curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
          
          # Install RVM
          curl -sSL https://get.rvm.io | bash -s stable
          
          # Source RVM
          source $HOME/.rvm/scripts/rvm
          
          # Install Ruby
          rvm install 3.1.4
          rvm use 3.1.4 --default
          
          # Verify installation
          ruby -v
      
      - name: Install dependencies
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
      
      - name: Fetch GitHub Projects
        run: |
          mkdir -p _data
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos" \
            -o _data/projects.json
      
      - name: Build site
        run: |
          source $HOME/.rvm/scripts/rvm
          JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site