name: Deploy Projects Page

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      RUBY_PATH: /opt/hostedtoolcache/Ruby/3.1.4/x64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential libssl-dev libreadline-dev zlib1g-dev \
            autoconf bison libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libyaml-dev \
            sqlite3 libgmp-dev
          
          # Install ruby-build
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX=/usr/local ./ruby-build/install.sh
      
      - name: Install Ruby
        run: |
          sudo mkdir -p $RUBY_PATH
          sudo chown -R $USER:$USER $(dirname $RUBY_PATH)
          
          # Build Ruby
          ruby-build 3.1.4 $RUBY_PATH
          touch $RUBY_PATH.complete
          
          # Add to PATH
          echo "$RUBY_PATH/bin" >> $GITHUB_PATH
          
          # Verify installation
          ruby -v
      
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
      
      - name: Fetch GitHub Projects
        run: |
          mkdir -p _data
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/repos" \
            -o _data/projects.json
      
      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site